-- Paladis · esquema para Supabase. Pégalo entero en SQL Editor y pulsa Run.

create table settings (
  id int primary key default 1 check (id = 1),
  name text not null default 'Paladis',
  whatsapp text not null,
  symbol text not null default '$'
);

create table categories (
  id text primary key,
  name text not null,
  icon text default '',
  sort int not null default 0
);

-- Grupos de opciones reutilizables (Tamaño, Leche...). choices = [["Regular",0],["Grande",1.5]]
create table option_groups (
  id bigint generated by default as identity primary key,
  label text not null,
  choices jsonb not null default '[]'
);

create table products (
  id bigint generated by default as identity primary key,
  cat text not null references categories(id) on update cascade,
  name text not null,
  description text default '',
  price numeric(10,2) not null check (price >= 0),
  emoji text default '',
  img text,
  active boolean not null default true,
  sort int not null default 0,
  opt_ids bigint[] not null default '{}',
  created_at timestamptz default now()
);

-- Quién puede administrar
create table admins (user_id uuid primary key references auth.users on delete cascade);

create function is_admin() returns boolean
language sql security definer stable set search_path = public
as $$ select exists (select 1 from admins where user_id = auth.uid()) $$;

-- Seguridad: todos leen el menú, solo los admins escriben
alter table settings enable row level security;
alter table categories enable row level security;
alter table option_groups enable row level security;
alter table products enable row level security;
alter table admins enable row level security;

create policy "leer" on settings for select using (true);
create policy "leer" on categories for select using (true);
create policy "leer" on option_groups for select using (true);
create policy "leer" on products for select using (active or is_admin());

create policy "admin" on settings for all to authenticated using (is_admin()) with check (is_admin());
create policy "admin" on categories for all to authenticated using (is_admin()) with check (is_admin());
create policy "admin" on option_groups for all to authenticated using (is_admin()) with check (is_admin());
create policy "admin" on products for all to authenticated using (is_admin()) with check (is_admin());

-- Fotos
insert into storage.buckets (id, name, public) values ('products', 'products', true) on conflict do nothing;
create policy "admin sube" on storage.objects for insert to authenticated with check (bucket_id = 'products' and is_admin());
create policy "admin edita" on storage.objects for update to authenticated using (bucket_id = 'products' and is_admin());
create policy "admin borra" on storage.objects for delete to authenticated using (bucket_id = 'products' and is_admin());

-- ===== Datos actuales =====
insert into settings (id, name, whatsapp, symbol) values (1, 'Paladis', '5353012038', '$');

insert into categories (id, name, icon, sort) values
  ('cafes', 'Cafés', '☕', 1), ('postres', 'Postres', '🍰', 2), ('frappes', 'Frappés', '🥤', 3),
  ('desayunos', 'Desayunos', '🥐', 4), ('tapas', 'Picaderas', '🧀', 5), ('cocteles', 'Cócteles', '🍹', 6);

insert into option_groups (id, label, choices) values
  (1, 'Tamaño', '[["Regular",0],["Grande",1.5]]'),
  (2, 'Leche', '[["Entera",0],["Avena",0.8],["Sin lactosa",0.5]]');

insert into products (id, cat, name, description, price, emoji, img, opt_ids) values
  (1, 'cafes', 'Espresso Doble', 'Grano de altura, cuerpo intenso y crema espesa.', 2.5, '☕', null, '{1}'),
  (2, 'cafes', 'Capuchino', 'Espresso, leche vaporizada y espuma sedosa.', 3.5, '☕', 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&q=70', '{1,2}'),
  (3, 'cafes', 'Latte de Vainilla', 'Suave, cremoso y con toque de vainilla natural.', 4, '🥛', null, '{1,2}'),
  (4, 'postres', 'Cupcake de Dulce de Leche', 'Esponjoso, con dulce de leche y galleta triturada.', 3, '🧁', null, '{}'),
  (5, 'postres', 'Donas Glaseadas', 'Suaves, con glaseado y toppings del día.', 2.5, '🍩', null, '{}'),
  (6, 'postres', 'Torta de Chocolate', 'Bizcocho húmedo con ganache de chocolate negro.', 4.5, '🍫', null, '{}'),
  (7, 'frappes', 'Frappé de Caramelo', 'Café helado, caramelo y crema batida.', 4.8, '🥤', null, '{1}'),
  (8, 'frappes', 'Frappé de Oreo', 'Cremoso, con galleta triturada y chocolate.', 5, '🍪', null, '{1}'),
  (9, 'desayunos', 'Tostada con Aguacate', 'Pan artesanal, aguacate, huevo pochado y limón.', 6, '🥑', null, '{}'),
  (10, 'desayunos', 'Croissant de Jamón y Queso', 'Horneado al momento, con mantequilla.', 4.5, '🥐', null, '{}'),
  (11, 'tapas', 'Tabla de Quesos', 'Selección de quesos, frutos secos y miel.', 9, '🧀', null, '{}'),
  (12, 'tapas', 'Croquetas Caseras (6u)', 'Cremosas por dentro, crujientes por fuera.', 5.5, '🍘', null, '{}'),
  (13, 'cocteles', 'Caipiríssima', 'Ron blanco, lima, azúcar y hielo picado.', 5, '🍹', null, '{}'),
  (14, 'cocteles', 'Mojito Clásico', 'Ron, hierbabuena fresca, lima y soda.', 5, '🍃', null, '{}'),
  (15, 'cocteles', 'Espresso Martini', 'Vodka, licor de café y espresso recién hecho.', 6.5, '🍸', null, '{}');

-- Los ids siguientes continúan después de los insertados
select setval(pg_get_serial_sequence('products', 'id'), 15);
select setval(pg_get_serial_sequence('option_groups', 'id'), 2);

-- ===== DESPUÉS de crear tu usuario en Authentication > Users, ejecuta esto con tu email =====
-- insert into admins (user_id) select id from auth.users where email = 'TU_EMAIL@ejemplo.com';
